services:
  audio-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/sofiiavarich/audioapi:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:2024.12.2
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    env_file: .env
    restart: unless-stopped
